/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikasir_irsannovita;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class MenuUtama extends javax.swing.JFrame {
        Connection konek;
        PreparedStatement pst;
        ResultSet rst;
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
         //this.setLocationRelativeTo(null);
         konek = Koneksi.koneksiDB();
         mulai();
         tampilWaktu();
    
    }
  public void mulai(){
        register.setEnabled(false);
        logout.setEnabled(false);
        master.setEnabled(false);
        transaksi.setEnabled(false);
        laporan.setEnabled(false);
        txttanggal.setEnabled(false);
        txtjam.setEnabled(false);
        FormLogin.setVisible(false);
        btnregister.setEnabled(false);
        btnpelanggan.setEnabled(false);
        btnproduk.setEnabled(false);
        btnpenjualan.setEnabled(false);
    }
    
    public void tampilWaktu(){
        Thread clock = new Thread(){
            public void run(){
                for (;;) {
                    Calendar cal = Calendar.getInstance();
                    SimpleDateFormat Jam = new SimpleDateFormat("HH:mm:ss");
                    SimpleDateFormat Tanggal = new SimpleDateFormat("yyyy-MM-dd");
                    txtjam.setText(Jam.format(cal.getTime()));
                    txttanggal.setText(Tanggal.format(cal.getTime()));
                try { sleep (1000);
                } catch (InterruptedException ex){
                    Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
            }
        };
        clock.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbluser = new javax.swing.JLabel();
        btnregister = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtjam = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        btnpelanggan = new javax.swing.JButton();
        btnproduk = new javax.swing.JButton();
        btnpenjualan = new javax.swing.JButton();
        FormLogin = new javax.swing.JInternalFrame();
        lblUsername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        cmbhakakses = new javax.swing.JComboBox<>();
        btnmasuk = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        beranda = new javax.swing.JMenu();
        register = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        login = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        pelanggan = new javax.swing.JMenuItem();
        produk = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        penjualan = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        Recaplaporan = new javax.swing.JMenuItem();
        tentang = new javax.swing.JMenu();
        Tentang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        lbluser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbluser.setText("Silahkan Login Dulu...!!!");

        btnregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-register-45.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        txtjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjamActionPerformed(evt);
            }
        });

        txttanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggalActionPerformed(evt);
            }
        });

        btnpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-customer-45.png"))); // NOI18N
        btnpelanggan.setText("Pelanggan");
        btnpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpelangganActionPerformed(evt);
            }
        });

        btnproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-product-45.png"))); // NOI18N
        btnproduk.setText("Produk");
        btnproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodukActionPerformed(evt);
            }
        });

        btnpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-fast-cart-45.png"))); // NOI18N
        btnpenjualan.setText("Penjualan");
        btnpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpenjualanActionPerformed(evt);
            }
        });

        FormLogin.setVisible(true);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-login-20.png"))); // NOI18N
        lblUsername.setText("LOGIN DISINI");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-20.png"))); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-password-20.png"))); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-access-20.png"))); // NOI18N
        jLabel5.setText("Hak Akses");

        cmbhakakses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "Admin", "Petugas", " " }));

        btnmasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-login-20.png"))); // NOI18N
        btnmasuk.setText("MASUK");
        btnmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasukActionPerformed(evt);
            }
        });

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cancel-20.png"))); // NOI18N
        btnbatal.setText("BATAL");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormLoginLayout = new javax.swing.GroupLayout(FormLogin.getContentPane());
        FormLogin.getContentPane().setLayout(FormLoginLayout);
        FormLoginLayout.setHorizontalGroup(
            FormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLoginLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(FormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(FormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbhakakses, 0, 153, Short.MAX_VALUE)
                    .addComponent(txtusername)
                    .addComponent(txtpassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FormLoginLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnmasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btnbatal)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addGap(206, 206, 206))
        );
        FormLoginLayout.setVerticalGroup(
            FormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLoginLayout.createSequentialGroup()
                .addComponent(lblUsername)
                .addGap(39, 39, 39)
                .addGroup(FormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(FormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(FormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbhakakses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(FormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmasuk)
                    .addComponent(btnbatal))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnpelanggan)
                        .addGap(35, 35, 35)
                        .addComponent(btnproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnpenjualan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(FormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpelanggan)
                    .addComponent(btnproduk)
                    .addComponent(btnpenjualan))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnregister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbluser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnregister)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-home-20.png"))); // NOI18N
        beranda.setText("Beranda");

        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-register-20 (1).png"))); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        beranda.add(register);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-logout-20 (1).png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        beranda.add(logout);

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-login-20.png"))); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        beranda.add(login);

        jMenuBar1.add(beranda);

        master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-master-20.png"))); // NOI18N
        master.setText("Master");

        pelanggan.setText("Pelanggan");
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        master.add(pelanggan);

        produk.setText("Produk");
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        master.add(produk);

        jMenuBar1.add(master);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-transaction-20.png"))); // NOI18N
        transaksi.setText("Transaksi");

        penjualan.setText("Penjualan");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        transaksi.add(penjualan);

        jMenuBar1.add(transaksi);

        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-report-20.png"))); // NOI18N
        laporan.setText("Laporan");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });

        Recaplaporan.setText("Recap Laporan");
        Recaplaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecaplaporanActionPerformed(evt);
            }
        });
        laporan.add(Recaplaporan);

        jMenuBar1.add(laporan);

        tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-about-20.png"))); // NOI18N
        tentang.setText("Help");
        tentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangActionPerformed(evt);
            }
        });

        Tentang.setText("Tentang");
        Tentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TentangActionPerformed(evt);
            }
        });
        tentang.add(Tentang);

        jMenuBar1.add(tentang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(387, 387, 387))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
    new FormPelanggan().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_pelangganActionPerformed

    private void btnprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodukActionPerformed
    new FormProduk().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_btnprodukActionPerformed

    private void btnpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpelangganActionPerformed
    new FormPelanggan().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_btnpelangganActionPerformed

    private void btnpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpenjualanActionPerformed
      new FormPenjualan().setVisible(true);            // TODO add your handling code here:
    }//GEN-LAST:event_btnpenjualanActionPerformed

    private void txttanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggalActionPerformed

    private void txtjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjamActionPerformed

    private void btnmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasukActionPerformed
       try {
        String sql = "select * from login where Username='"+txtusername.getText()+"' and Password='"+txtpassword.getText()+"' and HakAkses='"+cmbhakakses.getSelectedItem()+"'" ;
         pst = konek.prepareStatement(sql);
         rst = pst.executeQuery();
         if (rst.next()) {
             if (txtusername.getText().equals(rst.getString("Username")) &&txtpassword.getText().equals(rst.getString("Password")) &&cmbhakakses.getSelectedItem().equals(rst.getString("HakAkses")))
                if (cmbhakakses.getSelectedItem().equals("Admin")){
                        register.setEnabled(true);
                        logout.setEnabled(true);
                        master.setEnabled(true);
                        transaksi.setEnabled(true);
                        laporan.setEnabled(true);
                        txttanggal.setEnabled(false);
                        txtjam.setEnabled(false);
                        FormLogin.setVisible(false);
                        btnregister.setEnabled(true);
                        btnpelanggan.setEnabled(true);
                        btnproduk.setEnabled(true);
                        btnpenjualan.setEnabled(true);        
                 } else if (cmbhakakses.getSelectedItem().equals("Petugas")){  
                        register.setEnabled(false);
                        logout.setEnabled(true);
                        transaksi.setEnabled(true);
                        master.setEnabled(true);
                        transaksi.setEnabled(true);
                        laporan.setEnabled(true);
                        txttanggal.setEnabled(true);
                        txtjam.setEnabled(true);
                        FormLogin.setVisible(true);
                        btnregister.setEnabled(false);
                        btnpelanggan.setEnabled(true);
                        btnproduk.setEnabled(true);
                        btnpenjualan.setEnabled(true);
         }
             {
                JOptionPane.showMessageDialog(null, "Selamat Datang '"+txtusername.getText()+"'");
                    String text = txtusername.getText();
                   lbluser.setText(" Selamat Datang, "+text);
        }
        } else {
                JOptionPane.showMessageDialog(null, "Gagal Masuk, Periksa Kembali");
                    txtusername.setText("");
                    txtpassword.setText("");
                    cmbhakakses.setSelectedItem("-Pilih Salah Satu");
}

         } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Login Gagal");
      
}   // TODO add your handling code here:
    }//GEN-LAST:event_btnmasukActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
new MenuUtama().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnbatalActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
FormLogin.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
new FormRegister().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
new FormProduk().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_produkActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
new MenuUtama().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void RecaplaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecaplaporanActionPerformed
new FormLapTransaksi().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_RecaplaporanActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
new FormLapTransaksi().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_laporanActionPerformed

    private void tentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangActionPerformed
new FormAbout().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_tentangActionPerformed

    private void TentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TentangActionPerformed
new FormAbout().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_TentangActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
new FormPenjualan().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_penjualanActionPerformed

    
                                         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame FormLogin;
    private javax.swing.JMenuItem Recaplaporan;
    private javax.swing.JMenuItem Tentang;
    private javax.swing.JMenu beranda;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnmasuk;
    private javax.swing.JButton btnpelanggan;
    private javax.swing.JButton btnpenjualan;
    private javax.swing.JButton btnproduk;
    private javax.swing.JButton btnregister;
    private javax.swing.JComboBox<String> cmbhakakses;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu laporan;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbluser;
    private javax.swing.JMenuItem login;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem pelanggan;
    private javax.swing.JMenuItem penjualan;
    private javax.swing.JMenuItem produk;
    private javax.swing.JMenuItem register;
    private javax.swing.JMenu tentang;
    private javax.swing.JMenu transaksi;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
